# Site settings
title: twohealthybuns
description: "Two cousins on a mission to shape our buns by eating clean!"
baseurl: ""
url: "http://twohealthybuns.com"

# Build settings
markdown: kramdown
permalink: pretty
encoding: "UTF-8"
sass:
  style: :compressed